### ISSUE TITLE
TODO list

### ISSUE THREAD

**Issue by theunkn0wn1** [theunkn0wn1/Fuelrats-DispatchAssist#3]
Commands
------------
- [x] update system `/sys index system_eol` (anything after index is treated as part of the system)
- [x] update platform `/platform index platform`
- [x] update client name `/client index irc_name`
- [ ] update language
- [x] add rats `/assign rat1... ratn` -- `rat1` required, all others optional
- [x] remove rats `/unassign rat1..ratn`
- [x] generate stub case
- [x] delete case `/rm case` or `/del case`
- [ ] toggle active
- [ ] sync with Mecha
------------
